### ISSUE TITLE
"stop" doesn't clean up OVS bridges and ports

### ISSUE THREAD

**Issue by hzhou8** [numansiddique/ovn-fake-multinode#3]
It would be better to clean the data in OVS with "ovn_cluster.sh stop", at least the veth ports that have been deleted.
Example:

===
\# ovs-vsctl show
ad201bf8-53a3-4f5d-9caa-083cb54f62cd
    Bridge br-ovn
        Port "1606b3d910744_l"
            Interface "1606b3d910744_l"
                error: "could not open network device 1606b3d910744_l (No such device)"
        Port "19b576896cfd4_l"
            Interface "19b576896cfd4_l"
                error: "could not open network device 19b576896cfd4_l (No such device)"
        Port "992b4722dcf44_l"
            Interface "992b4722dcf44_l"
                error: "could not open network device 992b4722dcf44_l (No such device)"
        Port br-ovn
            Interface br-ovn
                type: internal
        Port ca26d1cb278d4_l
            Interface ca26d1cb278d4_l
                error: "could not open network device ca26d1cb278d4_l (No such device)"
    Bridge br-ovn-ext
        Port "5135b746fb944_l"
            Interface "5135b746fb944_l"
                error: "could not open network device 5135b746fb944_l (No such device)"
        Port "6ab4131675a34_l"
            Interface "6ab4131675a34_l"
                error: "could not open network device 6ab4131675a34_l (No such device)"
        Port br-ovn-ext
            Interface br-ovn-ext
                type: internal
        Port ovnfake-ext
            Interface ovnfake-ext
                type: internal
        Port aed6a21fc1e14_l
            Interface aed6a21fc1e14_l
                error: "could not open network device aed6a21fc1e14_l (No such device)"
        Port "133ea05991994_l"
            Interface "133ea05991994_l"
                error: "could not open network device 133ea05991994_l (No such device)"
    ovs_version: "2.12.90"

**Comment by numansiddique** [comment]
Agree. I will add it to my TODO.

**Comment by numansiddique** [comment]
Thanks.

**Comment by numansiddique** [comment]
The commit https://github.com/numansiddique/ovn-fake-multinode/commit/b51dde2cc50db4643e3f5224f06145ab18d72d5e fixes this issue.

I forgot to refer this issue in the commit message.
